# Generated by Django 6.1.1 on 2026-09-21 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.TextField(blank=True, choices=[('everyday', 'Everyday'), ('deep', 'Deep'), ('technical', 'Technical'), ('freestyle', 'Freestyle')], max_length=100)),
                ('description', models.CharField(blank=True)),
            ],
        ),
    ]
